kk-digital/kcg-ml-image-pipeline

scripts/test_minio_server.py
Adding a script to test minio server availibility.
=> adding a minio server testing script

orchestration/api/api_image.py, orchestration/api/api_job_stats.py
1- Added an API endpoint for getting the image details.
2- Added a job_stats api for getting stats about jobs by dataset and by job type.
=> Adding endpoints to api

scripts/test_prompt_image_generation.py
This script simply sample prompts from a provided csv, score it using the ELM scorer model and send prompts for image generation
=> add script for testing sending prompt jobs

scripts/prompt_mutator/greedy-substitution-search-v1.py, scripts/train_prompt_mutator.py, training_worker/prompt_mutator/binary_prompt_mutator.py, training_worker/prompt_mutator/prompt_mutator_model.py
1- optimised prompt mutator to increase generation speed.
2- made modifications to self training, data is now stored in batches of 10k datapoints and only the training data with the highest delta (difference between prediction and true value) is stored.
3- modified script to train a phrase permutation model.
=> Optimizing prompt mutator

input/dataset-config/propaganda-poster/base-prompts-propaganda-poster.csv, scripts/prompt_mutator/greedy-substitution-search-v1.py, training_worker/prompt_mutator/models/substitution_ranking_linear.py, training_worker/prompt_mutator/models/substitution_ranking_xgboost.py, training_worker/prompt_mutator/scripts/train_prompt_mutator.py, training_worker/prompt_mutator/self_training/self_training.py
1- Added independant approximation as an optional policy for initial prompt generation for the prompt mutator.
2- Implemented a phrase selection policy that is based on independant approximation when choosing phrases to substitute with.
=> Add independant approximation as an optional selection policy for the prompt mutator

orchestration/api/api_clip.py, orchestration/api/api_tag.py, orchestration/api/api_utils.py, orchestration/api/mongo_schemas.py
Reverts kk-digital/kcg-ml-image-pipeline#471
=> Revert "add new endpoints for tags"

orchestration/api/api_clip.py, orchestration/api/api_tag.py, orchestration/api/api_utils.py, orchestration/api/mongo_schemas.py
This reverts commit 813f6f89f92ec2d620c52178dbaf0773b1dbc127.
=> add new apis according standard

scripts/prompt_mutator/Iterative_painting.py, scripts/prompt_mutator/greedy_substitution_search_v1.py, utility/active_learning/active_learning.py, utility/boltzman/boltzman.py, worker/image_generation/scripts/inpaint_A1111.py, worker/worker.py
1- Refactored code for inpainting functions.
2- Updated the active learning pipeline to read directly from the orchestration api to fetch generated image data.
3- Updated iterative painting script.
=> Refactored inpainting functions and added functionalities to the active learning pipeline

configs/model_config.py, download_kandinsky_models.py, kandinsky/models/clip_image_encoder/clip_image_encoder.py, kandinsky/models/clip_text_encoder/clip_text_encoder.py, kandinsky/models/kandisky.py, kandinsky/pipelines/kandinsky_img2img.py, kandinsky/pipelines/kandinsky_inpainting.py, kandinsky/pipelines/kandinsky_prior.py, kandinsky/pipelines/kandinsky_text2img.py, utility/minio/cmd.py
1- Created a script for downloading kandinsky.
2- Created utilitiy classes and functions for kandinsky.
3- Created classes for CLIP text and image encoders used by kandinsky.
=> Implement kandinsky's code base and documentation into our pipeline

kandinsky/models/kandisky.py, kandinsky/pipelines/kandinsky_img2img.py, scripts/pez_optimisation_kandinsky.py, training_worker/ab_ranking/model/ab_ranking_fc.py, training_worker/latent_generator/train_fc_ab_ranking.py, utility/http/request.py, worker/prompt_generation/prompt_generator.py
1- Wrote a new class for An fc model.
2- Wrote script for generating a dataset and training the model.
3- Updated the task types in our prompt generators.
=> Wrote a model class and a training script for an FC model for predicting outpu clip scores.

kandinsky/models/kandisky.py, kandinsky_worker/self_training/training_utils.py, kandinsky_worker/worker.py, kandinsky_worker/worker_state.py, scripts/latent_search/gradient_descent_optimisation_kandinsky.py, training_worker/ab_ranking/model/ab_ranking_fc.py
1- Decreased memory usage by kandinsky's models.
2- Fixed some bugs in self training code.
=> Fixed issues with Kandinsky workers

training_worker/sampling/scripts/uniform_sampling_dataset.py
Removed additional step of re-calculating sphere assignments after sphere selection, to improve speed.
=> Updating the script for constructing uniform spheres

orchestration/api/api_clip.py, orchestration/api/api_dataset.py, orchestration/api/api_image.py, orchestration/api/api_job.py, orchestration/api/api_pseudo_tag.py, orchestration/api/api_ranking.py, orchestration/api/api_tag.py, orchestration/api/main.py, orchestration/api/mongo_schema/pseudo_tag_schemas.py, orchestration/api/mongo_schemas.py
Revert pr, due to an error in get-job endpoint that causes workers to not function correctly
=> Revert "Update  ranking, pseudo-tag and dataset apis "

orchestration/api/api_clip.py, orchestration/api/api_dataset.py, orchestration/api/api_image.py, orchestration/api/api_job.py, orchestration/api/api_pseudo_tag.py, orchestration/api/api_ranking.py, orchestration/api/api_tag.py, orchestration/api/main.py, orchestration/api/mongo_schema/pseudo_tag_schemas.py, orchestration/api/mongo_schemas.py
Reverts kk-digital/kcg-ml-image-pipeline#670
=> Revert "Revert "Update  ranking, pseudo-tag and dataset apis ""

orchestration/api/api_job.py, scripts/latent_search/proportional_sampling.py
Added a filter to the get-job endpoint to prioritize fetching jobs for variants in generation queue.
=> Update the get-job endpoint

orchestration/api/api_classifier_score.py, orchestration/api/main.py, scripts/image_classifier_scorer.py, scripts/latent_search/category_gaussian_sampling.py, training_worker/sampling/models/directional_gaussian_sampling_regression_fc.py, utility/http/request.py
=> Update the image-classifier-score to reduce runtime

orchestration/api/api_classifier.py, orchestration/api/api_classifier_score.py, scripts/latent_search/sphere_tree_search.py
1- Added endpoints to delete unessecary classifier models and scores.
2- Added randomly exploring search based on distance metric.
=> Removing unessecary classifier models and scores

inpainting_worker/worker.py, kandinsky/models/kandisky.py, kandinsky_worker/image_generation/img2img_generator.py, kandinsky_worker/worker.py, orchestration/api/api_ab_rank.py, scripts/kandinsky_test_generation.py, worker/worker.py
```
image_pair
num_images_above_min_score
num_image_pair_within_max_diff
```
```
"task_error_str": "Input type (float) and bias type (c10::Half) should be the same"
```
=> Fix some issues

inpainting_worker/worker.py, kandinsky_worker/worker.py, worker/worker.py
Fix bug in kandinsky worker
```
'GenerationTask' object has no attribute 'generation_task'
```
=> Fix bug in kandinsky woker

orchestration/api/api_ab_rank.py, orchestration/api/mongo_schemas.py, scripts/rank_ab_ranking_elm.py, scripts/rank_ab_ranking_linear.py
image_pair: List[Task]
image_score_pair: List[int]
num_images_above_min_score: float
num_image_pair_within_max_diff: float
=> Update response model of endpoint - ab_rank_image_pair 

orchestration/api/api_ingress_videos.py, orchestration/api/mongo_schemas.py
https://kcg.jetbrains.space/p/kcg-ml/issue-boards/kcg--ml/Sprint%2045?issues=KCG-ML-T-2284&expression=issue.ASSIGNEE%23%232HMsM71bvbk1
=> fix add-external-image-list and update add-ingress-video

orchestration/api/api_external_images.py, orchestration/api/api_ingress_videos.py, orchestration/api/api_utils.py, orchestration/api/main.py
Structure:
```
bucket: str
dataset; str
count: int
```
=> Add sequential id collection

orchestration/api/api_external_images.py, orchestration/api/api_ingress_videos.py, orchestration/api/api_utils.py
1- image file extension was obtained by image format of image file. so there is situation that file extension is JPEG, not jpg
2- fix the file path to include bucket name
```
{bucket}/{dataset}/0001/000001.jpg
```
=> fix bug in setting image file extension and path

orchestration/api/api_ingress_videos.py, orchestration/api/api_utils.py
These are the minio file paths for kcg-dataset-video-processing pipeline 
- Ingress video bucket for saving youtube video 
```
{video_game_name}/{short_hash}_[720p30fps.mp](https://720p30fps.mp4 
{video_game_name}/{short_hash}_720p30fps.json 
```
- External bucket for saving frames extracted from video 
```
{video_game_name}/0001/000001.jpg
```
=> refactor ingress video minio path

orchestration/api/api_ab_rank.py
endpoint
/ab-rank/get-ab-rank-image-pair
The endpoint occasionally returns same images because the MongoDB 'sample' aggregate query selects the same columns multiple times.
Additionally, the loading is very slow because it first filters through a large number of images before selecting them randomly.
=> fix issue in endpoint - get-ab-ranking-image-pair

orchestration/api/api_active_learning.py, orchestration/api/api_dataset.py, orchestration/api/api_image_by_rank.py, orchestration/api/api_ranking_model.py, orchestration/api/api_score.py, orchestration/api/main.py, orchestration/api/mongo_schema/ranking_models_schemas.py, orchestration/api/mongo_schemas.py, scripts/rank_ab_ranking_elm.py, scripts/rank_ab_ranking_linear.py, training_worker/ab_ranking/model/reports/get_model_card.py, utility/http/request.py
1- Created a new api for storing rank models.
2- Updated the rank scores api to store scores for each ranking model for each rank instead of storing one score per rank.
3- Updated the ranking model training scripts to register the models in mongoDB.
=> Created a new api for registering rank models

orchestration/api/api_all_images.py, orchestration/api/api_classifier_score.py, orchestration/api/api_external_images.py, orchestration/api/api_job.py, orchestration/api/api_rank_active_learning.py, orchestration/api/api_server_utility.py, orchestration/api/api_tag.py, orchestration/api/api_utils.py, orchestration/api/mongo_schema/tag_schemas.py, scripts/mongo_stat.py, scripts/update_ranking_datapoints.py, scripts/update_ranking_datapoints_minio.py, scripts/update_ranking_datapoints_mongo.py
added script to add image source field for each image metadata in ranking datapoints for MInio and for mongodb.
=> Update apis for ranking datapoints and added script

orchestration/api/api_video_game.py, orchestration/api/main.py, orchestration/api/mongo_schemas.py
add two properties - processed, game_id
schema
```
class VideoMetaData(BaseModel):
file_hash: str
filename: str
file_path: str
file_type: str
source_url: str
video_length: int
video_resolution: str
video_frame_rate: int
video_description: str
dataset: str
processed: bool
game_id: str
upload_date: str
```
```
class VideoGame(BaseModel):
game_id: str
title: str
description: str
```
=> Add video-game collection and Update the ingress-video collection

orchestration/api/api_ingress_videos.py, orchestration/api/mongo_schemas.py
Schema
```
class VideoMetaData(BaseModel):
file_hash: str
file_path: str
video_id: str
video_url: str
video_title: str
video_description: str
video_resolution: str
video_extension: str
video_length: int
video_filesize: int
video_frame_rate: int
video_language: str
processed: bool
game_id: str
upload_date: str
```
=> Update schema and endpoint for ingress-video

orchestration/api/api_score.py
The name of the new endpoint should be “/image-scores/scores/list- rank-scores”.
=> Endpoint - "/image-scores/scores/list- rank-scores"

orchestration/api/mongo_schema/all_images_schemas.py, orchestration/api/mongo_schema/extracts_schemas.py, orchestration/api/utils/uuid64.py
A new class for managing UUIDs was created. It includes some improvements:
- There are functions for converting the value to the correct string format.
- A problem with timezone was fixed.
- A better random numbers generator is used now.
I checked if the values are working as uint32 values as expected, and everything appears to be working well.
=> Uuid class

orchestration/api/api_external_images.py, orchestration/api/api_extracts.py, orchestration/api/api_ingress_videos.py, orchestration/api/api_rank_active_learning.py, orchestration/api/api_rank_active_learning_policy.py, orchestration/api/api_score.py, orchestration/api/api_tag.py, orchestration/api/api_video_game.py, orchestration/api/api_worker.py
This PR simplifies the code of about 19 delete API endpoints. This removes code and also makes the endpoints stiop making unneeded extra request to mongodb.
=> Simplify rest of the deletion endpoints

data_loader/tagged_data_loader.py, orchestration/api/api_clip.py, orchestration/api/api_external_images.py, orchestration/api/main.py, scripts/image_extraction/extract_images_from_dataset.py, scripts/image_extraction/utils.py, scripts/image_scorers/classifier_image_scorer.py, scripts/image_scorers/rank_image_scorer.py, utility/http/external_images_request.py
1- Added extra filtering steps to the image extraction script to select the best extract from each image.
2- Created a new endpoint for fetching only external images that don't have extracts in batches.
3- Created a new endpoint for getting clip vectors from prompts.
=> Made several improvements to the extraction script
